package netgloo.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, username, password).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the password for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "users")
public class User {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user's username
  @NotNull
  private String username;
  
  // The user's password
  @NotNull
  private String password;

  @NotNull
  private int priority;

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public User() { }

  public User(long id) { 
    this.id = id;
  }
  
  public User(String username, String password) {
    this.username = username;
    this.password = password;
    this.priority = 0;
  }

  // Getter and setter methods

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getUsername() {
    return username;
  }
  
  public void setUsername(String value) {
    this.username = value;
  }
  
  public String getPassword() {
    return password;
  }

  public void setPassword(String value) {
    this.password = value;
  }

  public int getPriority() {
    return priority;
  }

  public void setPriority(int value) {
    this.priority = value;
  }
  
} // class User
